Documented Cisco ACI Plugin Deployment Instructions
sunithasomanna/PluginCiscoACI pull request #1
Opened 2021-06-21 14:21 UTC by sunithasomanna

Drafted instructions for deploying Cisco ACI plugin in the readme.

2021-06-22 06:21 UTC, Bharath-KKB requested changes
This can be updated only after the ODIMRA deployment docs are updated to support kubernetes. We cant have the base product on docker and plugin on kubernetes .

2021-06-22 06:31 UTC, sukhwinder20 commented on README.md
> +5. Open the Dell plugin configuration YAML file.
Change Dell to ACI

2021-06-22 06:32 UTC, sukhwinder20 commented on README.md
> +   **Sample aciplugin-config.yaml file:**
Sample file is not correct missing other parameters

2021-06-22 06:33 UTC, sukhwinder20 commented on README.md
> +8. Save the Dell plugin Docker image on the deployment node at `~/plugins/aciplugin`.
Change the Dell to ACI

2021-06-22 06:35 UTC, sukhwinder20 commented on README.md
> +   <blockquote>
blockquote needs to be removed

2021-06-22 06:37 UTC, sukhwinder20 commented on README.md
> +      **Sample response \(URP manager\)**
Change example with ACI

2021-06-22 06:47 UTC, sukhwinder20 commented on README.md
> +   To know the status of this task, perform HTTP `GET` on the `taskmon` URI until the task is complete. If the plugin is added successfully, you will receive an HTTP `200 OK` status code.
Format needs to be changed here

2021-06-22 06:48 UTC, sukhwinder20 commented on README.md
> +   $ vi grfplugin_nginx_server.conf
change grf to aci

2021-06-22 06:50 UTC, sukhwinder20 commented on README.md
> +## Configuring proxy server for a plugin version
This section needs to be changed fully

2021-06-22 06:51 UTC, sukhwinder20 requested changes
Please address the changes

2021-06-28 18:28 UTC, sukhwinder20 commented on README.md
> +   **Sample aciplugin-config.yaml file:**
Sample file is not correct ,Kindly refer aci pdf guide

2021-06-28 18:36 UTC, sukhwinder20 commented on README.md
> +   **Sample aciplugin-config.yaml file:**
Also give the description for each parameter

2021-06-28 18:40 UTC, sukhwinder20 commented on README.md
> +    $ cd ~/ODIM/odim-controller/scripts
8th step in the pdf file needs to be run here "Update the following parameters in the kube_deploy_nodes.yaml file to their corresponding values:"

2021-06-28 18:46 UTC, sukhwinder20 commented on README.md
> +              "@odata.id":"/redfish/v1/Managers/536cee48-84b2-43dd-b6e2-2459ac0eeac6",
sample response is:

{
    "@odata.context": "/redfish/v1/$metadata#Manager.Manager",
    "@odata.id": "/redfish/v1/Managers/fb40f2dc-0c6d-4464-bc98-fea775adbbb9",
    "@odata.type": "#Manager.v1_10_0.Manager",
    "FirmwareVersion": "v1.0.0",
    "Id": "fb40f2dc-0c6d-4464-bc98-fea775adbbb9",
    "Links": {
        "ManagerForSwitches": [
            {
                "@odata.id": "/redfish/v1/Fabrics/fb40f2dc-0c6d-4464-bc98-fea775adbbb9:1/Switches/af10c386-68d5-45aa-b3c3-431e3e4c3647:101"
            },
            {
                "@odata.id": "/redfish/v1/Fabrics/fb40f2dc-0c6d-4464-bc98-fea775adbbb9:1/Switches/668f20cf-b6e7-4ded-a180-bf8e33dc18fc:102"
            },
            {
                "@odata.id": "/redfish/v1/Fabrics/fb40f2dc-0c6d-4464-bc98-fea775adbbb9:1/Switches/7d5a25b3-3ac4-49f4-a929-243b5b97bba0:201"
            }
        ],
        "ManagerForSwitches@odata.count": 3
    },
    "ManagerType": "Service",
    "Name": "ACI",
    "Status": {
        "Health": "OK",
        "State": "Enabled"
    },
    "UUID": "fb40f2dc-0c6d-4464-bc98-fea775adbbb9"
}

2021-06-28 18:48 UTC, sukhwinder20 commented on README.md
> +
4th point should be default zone

2021-06-28 18:49 UTC, sukhwinder20 commented on README.md
> +"Upper": 200
Arrange the brackets properly

2021-06-28 18:52 UTC, sukhwinder20 commented on README.md
> +| Name        | String (optional)     | Name for the zone.<br />**NOTE**: Ensure that there are no spaces. |
<br /> needs to be removed

2021-06-28 18:53 UTC, sukhwinder20 commented on README.md
> +| Description | String (optional)     | The description for the zone.                                |
Add **NOTE**: Ensure that there are no spaces

2021-07-19 11:03 UTC, sukhwinder20 approved these changes

2021-07-20 06:02 UTC, ashraf-vazeer approved these changes

2021-07-20 07:24 UTC, merged