added a new step to navigate to odim dir before saving proxy config file in ACI plugin deployment procedure
sunithasomanna/PluginCiscoACI pull request #4
Opened 2022-02-02 07:24 UTC by sunithasomanna

added a new step to navigate to odim dir before saving proxy config file in ACI plugin deployment procedure in ACI readme

2022-02-03 04:21 UTC, irappa-pattar approved these changes

2022-02-03 04:33 UTC, jeevan-kamkar approved these changes

2022-02-09 06:08 UTC, amar-shalgar approved these changes

2022-02-09 08:25 UTC, sukhwinder20 commented on README.md
>     docker save aciplugin:1.0 -o ~/plugins/aciplugin/aciplugin.tar
Change aciplugin:1.0 to aciplugin:2.0

2022-02-09 08:26 UTC, sukhwinder20 commented on README.md
>     docker save aciplugin:1.0 -o ~/plugins/aciplugin/aciplugin.tar
Change aciplugin:1.0 to aciplugin:2.0

2022-02-09 08:27 UTC, sukhwinder20 requested changes
Please address the comment

2022-02-09 09:05 UTC, sunithasomanna commented on README.md
>     docker save aciplugin:1.0 -o ~/plugins/aciplugin/aciplugin.tar
done

2022-02-09 09:06 UTC, sunithasomanna commented
> Please address the comment

done

2022-02-09 09:48 UTC, sukhwinder20 approved these changes

2022-02-10 09:18 UTC, shivacharanms approved these changes

2022-02-10 09:18 UTC, merged