Updating relevant feedback items given for the plugin sections in the Getting Started readme
sunithasomanna/PluginCiscoACI pull request #6
Opened 2022-02-22 12:42 UTC by sunithasomanna

- Updating relevant feedback items given for the plugin sections in the Getting Started readme:
- Update parameters for ACI plugin (step 13)
- Specify what is default odim_username and odim_password in the section "Adding a plugin into the Resource Aggregator for ODIM framework"
- Replace hardcoded connectionMethodID in sample payload of aci plugin with a variable {ConnectionMethodId} in the section "Adding a plugin into the Resource Aggregator for ODIM framework".
- To verify the added plugins, need to call 2 APIs. Rephrase to this - " A link of the executed task. Performing a GET operation on this task displays the task monitor associated with this operation in the response header".

2022-02-24 04:11 UTC, sukhwinder20 commented on README.md
> +13. Specify values for the following parameters in the `kube_deploy_nodes.yaml` file:
cd ODIM --> This has to be removed

2022-02-24 04:37 UTC, sunithasomanna commented on README.md
> +13. Specify values for the following parameters in the `kube_deploy_nodes.yaml` file:
removed

2022-02-24 09:59 UTC, irappa-pattar approved these changes

2022-02-24 10:28 UTC, jeevan-kamkar approved these changes

2022-02-25 08:36 UTC, sukhwinder20 commented on README.md
Add cd ~/PluginCiscoACI in 10th step

2022-02-25 08:37 UTC, sukhwinder20 requested changes
Kindly address the comment

2022-02-25 08:56 UTC, sunithasomanna commented on README.md
done

2022-02-25 09:38 UTC, sukhwinder20 approved these changes
LGTM

2022-02-25 16:14 UTC, shivacharanms approved these changes

2022-02-25 16:16 UTC, merged